// This file is auto-generated by @hey-api/openapi-ts
import {
    type Client,
    type Options as Options2,
    type TDataShape,
    formDataBodySerializer,
} from './client';
import { client } from './client.gen';
import type {
    AddMemberData,
    AddMemberResponses,
    AddTicketTypeToEventData,
    AddTicketTypeToEventResponses,
    CheckInTicketData,
    CheckInTicketResponses,
    CreateEventData,
    CreateEventResponses,
    CreateOrderData,
    CreateOrderResponses,
    CreateOrganizationData,
    CreateOrganizationResponses,
    GetAllEventsData,
    GetAllEventsResponses,
    GetAllOrganizationsData,
    GetAllOrganizationsResponses,
    GetCurrentUserData,
    GetCurrentUserResponses,
    GetDashboardData,
    GetDashboardResponses,
    GetEventByIdData,
    GetEventByIdResponses,
    GetEventsByOrganizationData,
    GetEventsByOrganizationResponses,
    GetMembersData,
    GetMembersResponses,
    GetMyOrderHistoryData,
    GetMyOrderHistoryResponses,
    GetMyOrganizationsData,
    GetMyOrganizationsResponses,
    GetOrdersData,
    GetOrdersResponses,
    GetTicketsData,
    GetTicketsResponses,
    HandleChatMessageData,
    HandleChatMessageResponses,
    HandleVnpayIpnData,
    HandleVnpayIpnResponses,
    RemoveMemberData,
    RemoveMemberResponses,
    UpdateEventData,
    UpdateEventResponses,
    UpdateOrgStatusData,
    UpdateOrgStatusResponses,
    UpdateOrganizationData,
    UpdateOrganizationResponses,
    UpdateProfileData,
    UpdateProfileResponses,
    UpdateTicketTypeData,
    UpdateTicketTypeResponses,
    UploadData,
    UploadResponses,
} from './types.gen';

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getCurrentUser = <ThrowOnError extends boolean = false>(
    options?: Options<GetCurrentUserData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetCurrentUserResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/users/me',
        ...options,
    });
};

export const updateProfile = <ThrowOnError extends boolean = false>(
    options?: Options<UpdateProfileData, ThrowOnError>,
) => {
    return (options?.client ?? client).put<
        UpdateProfileResponses,
        unknown,
        ThrowOnError
    >({
        ...formDataBodySerializer,
        url: '/api/v1/users/me',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers,
        },
    });
};

export const updateOrganization = <ThrowOnError extends boolean = false>(
    options: Options<UpdateOrganizationData, ThrowOnError>,
) => {
    return (options.client ?? client).put<
        UpdateOrganizationResponses,
        unknown,
        ThrowOnError
    >({
        ...formDataBodySerializer,
        url: '/api/v1/organizer/organizations/{orgId}',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers,
        },
    });
};

export const upload = <ThrowOnError extends boolean = false>(
    options?: Options<UploadData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<
        UploadResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/upload',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    });
};

export const getMyOrganizations = <ThrowOnError extends boolean = false>(
    options?: Options<GetMyOrganizationsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetMyOrganizationsResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/organizations',
        ...options,
    });
};

export const createOrganization = <ThrowOnError extends boolean = false>(
    options?: Options<CreateOrganizationData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<
        CreateOrganizationResponses,
        unknown,
        ThrowOnError
    >({
        ...formDataBodySerializer,
        url: '/api/v1/organizer/organizations',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers,
        },
    });
};

export const getMembers = <ThrowOnError extends boolean = false>(
    options: Options<GetMembersData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GetMembersResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/organizations/{orgId}/members',
        ...options,
    });
};

export const addMember = <ThrowOnError extends boolean = false>(
    options: Options<AddMemberData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        AddMemberResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/organizations/{orgId}/members',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
};

export const getEventsByOrganization = <ThrowOnError extends boolean = false>(
    options: Options<GetEventsByOrganizationData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GetEventsByOrganizationResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/organizations/{orgId}/events',
        ...options,
    });
};

export const createEvent = <ThrowOnError extends boolean = false>(
    options: Options<CreateEventData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        CreateEventResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/organizations/{orgId}/events',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
};

export const addTicketTypeToEvent = <ThrowOnError extends boolean = false>(
    options: Options<AddTicketTypeToEventData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        AddTicketTypeToEventResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/events/{eventId}/ticketTypes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
};

export const checkInTicket = <ThrowOnError extends boolean = false>(
    options: Options<CheckInTicketData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        CheckInTicketResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/events/{eventId}/checkIn',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
};

export const createOrder = <ThrowOnError extends boolean = false>(
    options: Options<CreateOrderData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        CreateOrderResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/orders',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
};

export const handleChatMessage = <ThrowOnError extends boolean = false>(
    options: Options<HandleChatMessageData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        HandleChatMessageResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/chat',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
};

export const updateTicketType = <ThrowOnError extends boolean = false>(
    options: Options<UpdateTicketTypeData, ThrowOnError>,
) => {
    return (options.client ?? client).patch<
        UpdateTicketTypeResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/ticketTypes/{ticketTypeId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
};

export const updateEvent = <ThrowOnError extends boolean = false>(
    options: Options<UpdateEventData, ThrowOnError>,
) => {
    return (options.client ?? client).patch<
        UpdateEventResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/events/{eventId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
};

export const updateOrgStatus = <ThrowOnError extends boolean = false>(
    options: Options<UpdateOrgStatusData, ThrowOnError>,
) => {
    return (options.client ?? client).patch<
        UpdateOrgStatusResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/admin/organizations/{orgId}/status',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    });
};

export const getTickets = <ThrowOnError extends boolean = false>(
    options?: Options<GetTicketsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetTicketsResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/users/me/tickets',
        ...options,
    });
};

export const getMyOrderHistory = <ThrowOnError extends boolean = false>(
    options?: Options<GetMyOrderHistoryData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetMyOrderHistoryResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/users/me/orders',
        ...options,
    });
};

export const handleVnpayIpn = <ThrowOnError extends boolean = false>(
    options?: Options<HandleVnpayIpnData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        HandleVnpayIpnResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/payment/vnpay-ipn',
        ...options,
    });
};

export const getOrders = <ThrowOnError extends boolean = false>(
    options: Options<GetOrdersData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GetOrdersResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/organizations/{orgId}/orders',
        ...options,
    });
};

export const getDashboard = <ThrowOnError extends boolean = false>(
    options: Options<GetDashboardData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GetDashboardResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/organizations/{orgId}/dashboard',
        ...options,
    });
};

export const getAllEvents = <ThrowOnError extends boolean = false>(
    options?: Options<GetAllEventsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetAllEventsResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/events',
        ...options,
    });
};

export const getEventById = <ThrowOnError extends boolean = false>(
    options: Options<GetEventByIdData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GetEventByIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/events/{eventId}',
        ...options,
    });
};

export const getAllOrganizations = <ThrowOnError extends boolean = false>(
    options?: Options<GetAllOrganizationsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetAllOrganizationsResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/admin/organizations',
        ...options,
    });
};

export const removeMember = <ThrowOnError extends boolean = false>(
    options: Options<RemoveMemberData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<
        RemoveMemberResponses,
        unknown,
        ThrowOnError
    >({
        url: '/api/v1/organizer/organizations/{orgId}/members/{userId}',
        ...options,
    });
};
