// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://src` | (string & {});
};

export type UserUpdateDto = {
    fullName?: string;
    phoneNumber?: string;
    address?: string;
    avatar?: Blob | File;
};

export type PagedResult = {
    pageNumber?: number;
    pageSize?: number;
    totalElements?: number;
    totalPages?: number;
};

export type Response = {
    serverDateTime?: string;
    status?: number;
    code?: number;
    message?: string;
    exception?: string;
    traceId?: string;
    data?: unknown;
    pagedResult?: PagedResult;
};

export type OrganizationRequestDto = {
    name?: string;
    description?: string;
    email?: string;
    phoneNumber?: string;
    address?: string;
    logo?: Blob | File;
};

export type MemberRequestDto = {
    email: string;
    role: 'OWNER' | 'MANAGER' | 'STAFF';
};

export type EventCreateRequestDto = {
    title: string;
    description?: string;
    startDate: string;
    endDate: string;
    location: string;
    bannerImage?: Blob | File;
    ticketTypes: Array<TicketTypeRequestDto>;
};

export type TicketTypeRequestDto = {
    type: string;
    price?: number;
    totalQuantity?: number;
    ticketTypeStatus?: 'ACTIVE' | 'SOLD_OUT' | 'CANCELED';
};

export type CheckInRequestDto = {
    qrCode: string;
};

export type OrderItemRequestDto = {
    ticketTypeId: number;
    quantity?: number;
};

export type OrderRequestDto = {
    fullName?: string;
    email?: string;
    phoneNumber?: string;
    items: Array<OrderItemRequestDto>;
};

export type ChatRequestDto = {
    message: string;
};

export type EventUpdateRequestDto = {
    title?: string;
    description?: string;
    location?: string;
    startDate?: string;
    endDate?: string;
    bannerImage?: Blob | File;
};

export type OrgStatusUpdateDto = {
    status?: 'ACTIVE' | 'INACTIVE' | 'PENDING';
};

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetCurrentUserResponse =
    GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type UpdateProfileData = {
    body?: UserUpdateDto;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateProfileResponses = {
    /**
     * OK
     */
    200: Response;
};

export type UpdateProfileResponse =
    UpdateProfileResponses[keyof UpdateProfileResponses];

export type UpdateOrganizationData = {
    body?: OrganizationRequestDto;
    path: {
        orgId: number;
    };
    query?: never;
    url: '/api/v1/organizer/organizations/{orgId}';
};

export type UpdateOrganizationResponses = {
    /**
     * OK
     */
    200: Response;
};

export type UpdateOrganizationResponse =
    UpdateOrganizationResponses[keyof UpdateOrganizationResponses];

export type UploadData = {
    body?: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/v1/upload';
};

export type UploadResponses = {
    /**
     * OK
     */
    200: Response;
};

export type UploadResponse = UploadResponses[keyof UploadResponses];

export type GetMyOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizer/organizations';
};

export type GetMyOrganizationsResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetMyOrganizationsResponse =
    GetMyOrganizationsResponses[keyof GetMyOrganizationsResponses];

export type CreateOrganizationData = {
    body?: OrganizationRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/organizer/organizations';
};

export type CreateOrganizationResponses = {
    /**
     * OK
     */
    200: Response;
};

export type CreateOrganizationResponse =
    CreateOrganizationResponses[keyof CreateOrganizationResponses];

export type GetMembersData = {
    body?: never;
    path: {
        orgId: number;
    };
    query?: never;
    url: '/api/v1/organizer/organizations/{orgId}/members';
};

export type GetMembersResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetMembersResponse = GetMembersResponses[keyof GetMembersResponses];

export type AddMemberData = {
    body: MemberRequestDto;
    path: {
        orgId: number;
    };
    query?: never;
    url: '/api/v1/organizer/organizations/{orgId}/members';
};

export type AddMemberResponses = {
    /**
     * OK
     */
    200: Response;
};

export type AddMemberResponse = AddMemberResponses[keyof AddMemberResponses];

export type GetEventsByOrganizationData = {
    body?: never;
    path: {
        orgId: number;
    };
    query?: never;
    url: '/api/v1/organizer/organizations/{orgId}/events';
};

export type GetEventsByOrganizationResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetEventsByOrganizationResponse =
    GetEventsByOrganizationResponses[keyof GetEventsByOrganizationResponses];

export type CreateEventData = {
    body?: EventCreateRequestDto;
    path: {
        orgId: number;
    };
    query?: never;
    url: '/api/v1/organizer/organizations/{orgId}/events';
};

export type CreateEventResponses = {
    /**
     * Created
     */
    201: Response;
};

export type CreateEventResponse =
    CreateEventResponses[keyof CreateEventResponses];

export type AddTicketTypeToEventData = {
    body: TicketTypeRequestDto;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/api/v1/organizer/events/{eventId}/ticketTypes';
};

export type AddTicketTypeToEventResponses = {
    /**
     * Created
     */
    201: Response;
};

export type AddTicketTypeToEventResponse =
    AddTicketTypeToEventResponses[keyof AddTicketTypeToEventResponses];

export type CheckInTicketData = {
    body: CheckInRequestDto;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/api/v1/organizer/events/{eventId}/checkIn';
};

export type CheckInTicketResponses = {
    /**
     * OK
     */
    200: Response;
};

export type CheckInTicketResponse =
    CheckInTicketResponses[keyof CheckInTicketResponses];

export type CreateOrderData = {
    body: OrderRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/orders';
};

export type CreateOrderResponses = {
    /**
     * OK
     */
    200: Response;
};

export type CreateOrderResponse =
    CreateOrderResponses[keyof CreateOrderResponses];

export type HandleChatMessageData = {
    body: ChatRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/chat';
};

export type HandleChatMessageResponses = {
    /**
     * OK
     */
    200: Response;
};

export type HandleChatMessageResponse =
    HandleChatMessageResponses[keyof HandleChatMessageResponses];

export type UpdateTicketTypeData = {
    body: TicketTypeRequestDto;
    path: {
        ticketTypeId: number;
    };
    query?: never;
    url: '/api/v1/organizer/ticketTypes/{ticketTypeId}';
};

export type UpdateTicketTypeResponses = {
    /**
     * OK
     */
    200: Response;
};

export type UpdateTicketTypeResponse =
    UpdateTicketTypeResponses[keyof UpdateTicketTypeResponses];

export type UpdateEventData = {
    body?: EventUpdateRequestDto;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/api/v1/organizer/events/{eventId}';
};

export type UpdateEventResponses = {
    /**
     * OK
     */
    200: Response;
};

export type UpdateEventResponse =
    UpdateEventResponses[keyof UpdateEventResponses];

export type UpdateOrgStatusData = {
    body: OrgStatusUpdateDto;
    path: {
        orgId: number;
    };
    query?: never;
    url: '/api/v1/admin/organizations/{orgId}/status';
};

export type UpdateOrgStatusResponses = {
    /**
     * OK
     */
    200: Response;
};

export type UpdateOrgStatusResponse =
    UpdateOrgStatusResponses[keyof UpdateOrgStatusResponses];

export type GetTicketsData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'ACTIVE' | 'USED' | 'CANCELED';
    };
    url: '/api/v1/users/me/tickets';
};

export type GetTicketsResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetTicketsResponse = GetTicketsResponses[keyof GetTicketsResponses];

export type GetMyOrderHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/orders';
};

export type GetMyOrderHistoryResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetMyOrderHistoryResponse =
    GetMyOrderHistoryResponses[keyof GetMyOrderHistoryResponses];

export type HandleVnpayIpnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/payment/vnpay-ipn';
};

export type HandleVnpayIpnResponses = {
    /**
     * OK
     */
    200: Response;
};

export type HandleVnpayIpnResponse =
    HandleVnpayIpnResponses[keyof HandleVnpayIpnResponses];

export type GetOrdersData = {
    body?: never;
    path: {
        orgId: number;
    };
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/v1/organizer/organizations/{orgId}/orders';
};

export type GetOrdersResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetOrdersResponse = GetOrdersResponses[keyof GetOrdersResponses];

export type GetDashboardData = {
    body?: never;
    path: {
        orgId: number;
    };
    query?: never;
    url: '/api/v1/organizer/organizations/{orgId}/dashboard';
};

export type GetDashboardResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetDashboardResponse =
    GetDashboardResponses[keyof GetDashboardResponses];

export type GetAllEventsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
        direction?: 'ASC' | 'DESC';
        attribute?: string;
        title?: string;
        startDate?: string;
        endDate?: string;
        location?: string;
    };
    url: '/api/v1/events';
};

export type GetAllEventsResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetAllEventsResponse =
    GetAllEventsResponses[keyof GetAllEventsResponses];

export type GetEventByIdData = {
    body?: never;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/api/v1/events/{eventId}';
};

export type GetEventByIdResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetEventByIdResponse =
    GetEventByIdResponses[keyof GetEventByIdResponses];

export type GetAllOrganizationsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
        direction?: 'ASC' | 'DESC';
        attribute?: string;
        name?: string;
        email?: string;
        status?: 'ACTIVE' | 'INACTIVE' | 'PENDING';
        createdAfter?: string;
        createdBefore?: string;
    };
    url: '/api/v1/admin/organizations';
};

export type GetAllOrganizationsResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetAllOrganizationsResponse =
    GetAllOrganizationsResponses[keyof GetAllOrganizationsResponses];

export type RemoveMemberData = {
    body?: never;
    path: {
        orgId: number;
        userId: number;
    };
    query?: never;
    url: '/api/v1/organizer/organizations/{orgId}/members/{userId}';
};

export type RemoveMemberResponses = {
    /**
     * OK
     */
    200: Response;
};

export type RemoveMemberResponse =
    RemoveMemberResponses[keyof RemoveMemberResponses];
