// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://ec2-13-250-47-128.ap-southeast-1.compute.amazonaws.com:8080' | (string & {});
};

export type EventCreateRequestDto = {
    title: string;
    description?: string;
    startDate: string;
    endDate: string;
    location: string;
    ticketTypes: Array<TicketTypeRequestDto>;
};

export type TicketTypeRequestDto = {
    type: string;
    price?: number;
    totalQuantity?: number;
    ticketTypeStatus?: 'ACTIVE' | 'SOLD_OUT' | 'CANCELED';
};

export type PagedResult = {
    pageNumber?: number;
    pageSize?: number;
    totalElements?: number;
    totalPages?: number;
};

export type Response = {
    serverDateTime?: string;
    status?: number;
    code?: number;
    message?: string;
    exception?: string;
    traceId?: string;
    data?: unknown;
    pagedResult?: PagedResult;
};

export type CheckInRequestDto = {
    qrCode: string;
};

export type OrderItemRequestDto = {
    ticketTypeId: number;
    quantity?: number;
};

export type OrderRequestDto = {
    items: Array<OrderItemRequestDto>;
};

export type EventUpdateRequestDto = {
    title?: string;
    description?: string;
    location?: string;
    startDate?: string;
    endDate?: string;
};

export type GetEventsByOrganizationData = {
    body?: never;
    path: {
        orgId: number;
    };
    query?: never;
    url: '/api/v1/organizer/organizations/{orgId}/events';
};

export type GetEventsByOrganizationResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetEventsByOrganizationResponse = GetEventsByOrganizationResponses[keyof GetEventsByOrganizationResponses];

export type CreateEventData = {
    body: EventCreateRequestDto;
    path: {
        orgId: number;
    };
    query?: never;
    url: '/api/v1/organizer/organizations/{orgId}/events';
};

export type CreateEventResponses = {
    /**
     * Created
     */
    201: Response;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type AddTicketTypeToEventData = {
    body: TicketTypeRequestDto;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/api/v1/organizer/events/{eventId}/ticketTypes';
};

export type AddTicketTypeToEventResponses = {
    /**
     * Created
     */
    201: Response;
};

export type AddTicketTypeToEventResponse = AddTicketTypeToEventResponses[keyof AddTicketTypeToEventResponses];

export type CheckInTicketData = {
    body: CheckInRequestDto;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/api/v1/organizer/events/{eventId}/checkIn';
};

export type CheckInTicketResponses = {
    /**
     * OK
     */
    200: Response;
};

export type CheckInTicketResponse = CheckInTicketResponses[keyof CheckInTicketResponses];

export type CreateOrderData = {
    body: OrderRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/orders';
};

export type CreateOrderResponses = {
    /**
     * OK
     */
    200: Response;
};

export type CreateOrderResponse = CreateOrderResponses[keyof CreateOrderResponses];

export type UpdateTicketTypeData = {
    body: TicketTypeRequestDto;
    path: {
        ticketTypeId: number;
    };
    query?: never;
    url: '/api/v1/organizer/ticketTypes/{ticketTypeId}';
};

export type UpdateTicketTypeResponses = {
    /**
     * OK
     */
    200: Response;
};

export type UpdateTicketTypeResponse = UpdateTicketTypeResponses[keyof UpdateTicketTypeResponses];

export type UpdateEventData = {
    body: EventUpdateRequestDto;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/api/v1/organizer/events/{eventId}';
};

export type UpdateEventResponses = {
    /**
     * OK
     */
    200: Response;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetTicketsData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'ACTIVE' | 'USED' | 'CANCELED';
    };
    url: '/api/v1/users/me/tickets';
};

export type GetTicketsResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetTicketsResponse = GetTicketsResponses[keyof GetTicketsResponses];

export type GetMyOrderHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/orders';
};

export type GetMyOrderHistoryResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetMyOrderHistoryResponse = GetMyOrderHistoryResponses[keyof GetMyOrderHistoryResponses];

export type HandleVnpayIpnData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/payment/vnpay-ipn';
};

export type HandleVnpayIpnResponses = {
    /**
     * OK
     */
    200: Response;
};

export type HandleVnpayIpnResponse = HandleVnpayIpnResponses[keyof HandleVnpayIpnResponses];

export type GetMyOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizer/organizations';
};

export type GetMyOrganizationsResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetMyOrganizationsResponse = GetMyOrganizationsResponses[keyof GetMyOrganizationsResponses];

export type GetAllEventsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
        direction?: 'ASC' | 'DESC';
        attribute?: string;
        title?: string;
        startDate?: string;
        endDate?: string;
        location?: string;
    };
    url: '/api/v1/events';
};

export type GetAllEventsResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetAllEventsResponse = GetAllEventsResponses[keyof GetAllEventsResponses];

export type GetEventByIdData = {
    body?: never;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/api/v1/events/{eventId}';
};

export type GetEventByIdResponses = {
    /**
     * OK
     */
    200: Response;
};

export type GetEventByIdResponse = GetEventByIdResponses[keyof GetEventByIdResponses];
