/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizerRouteRouteImport } from './routes/organizer/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as PaymentResultIndexRouteImport } from './routes/payment-result/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer/index'
import { Route as MyTicketsIndexRouteImport } from './routes/my-tickets/index'
import { Route as OrganizerCheckInIndexRouteImport } from './routes/organizer/check-in/index'
import { Route as OrganizerOrgIdIndexRouteImport } from './routes/organizer/$orgId/index'
import { Route as Oauth2RedirectIndexRouteImport } from './routes/oauth2/redirect/index'
import { Route as EventEventIdIndexRouteImport } from './routes/event/$eventId/index'
import { Route as OrganizerOrgIdCheckInIndexRouteImport } from './routes/organizer/$orgId/check-in/index'
import { Route as EventEventIdPaymentIndexRouteImport } from './routes/event/$eventId/payment/index'
import { Route as OrganizerOrgIdEventEventIdIndexRouteImport } from './routes/organizer/$orgId/event/$eventId/index'
import { Route as EventEventIdPaymentConfirmIndexRouteImport } from './routes/event/$eventId/payment/confirm/index'
import { Route as OrganizerOrgIdEventEventIdCheckInIndexRouteImport } from './routes/organizer/$orgId/event/$eventId/check-in/index'

const OrganizerRouteRoute = OrganizerRouteRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultIndexRoute = PaymentResultIndexRouteImport.update({
  id: '/payment-result/',
  path: '/payment-result/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRouteRoute,
} as any)
const MyTicketsIndexRoute = MyTicketsIndexRouteImport.update({
  id: '/my-tickets/',
  path: '/my-tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerCheckInIndexRoute = OrganizerCheckInIndexRouteImport.update({
  id: '/check-in/',
  path: '/check-in/',
  getParentRoute: () => OrganizerRouteRoute,
} as any)
const OrganizerOrgIdIndexRoute = OrganizerOrgIdIndexRouteImport.update({
  id: '/$orgId/',
  path: '/$orgId/',
  getParentRoute: () => OrganizerRouteRoute,
} as any)
const Oauth2RedirectIndexRoute = Oauth2RedirectIndexRouteImport.update({
  id: '/oauth2/redirect/',
  path: '/oauth2/redirect/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdIndexRoute = EventEventIdIndexRouteImport.update({
  id: '/event/$eventId/',
  path: '/event/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerOrgIdCheckInIndexRoute =
  OrganizerOrgIdCheckInIndexRouteImport.update({
    id: '/$orgId/check-in/',
    path: '/$orgId/check-in/',
    getParentRoute: () => OrganizerRouteRoute,
  } as any)
const EventEventIdPaymentIndexRoute =
  EventEventIdPaymentIndexRouteImport.update({
    id: '/event/$eventId/payment/',
    path: '/event/$eventId/payment/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerOrgIdEventEventIdIndexRoute =
  OrganizerOrgIdEventEventIdIndexRouteImport.update({
    id: '/$orgId/event/$eventId/',
    path: '/$orgId/event/$eventId/',
    getParentRoute: () => OrganizerRouteRoute,
  } as any)
const EventEventIdPaymentConfirmIndexRoute =
  EventEventIdPaymentConfirmIndexRouteImport.update({
    id: '/event/$eventId/payment/confirm/',
    path: '/event/$eventId/payment/confirm/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerOrgIdEventEventIdCheckInIndexRoute =
  OrganizerOrgIdEventEventIdCheckInIndexRouteImport.update({
    id: '/$orgId/event/$eventId/check-in/',
    path: '/$orgId/event/$eventId/check-in/',
    getParentRoute: () => OrganizerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRouteRouteWithChildren
  '/my-tickets': typeof MyTicketsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/payment-result': typeof PaymentResultIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/event/$eventId': typeof EventEventIdIndexRoute
  '/oauth2/redirect': typeof Oauth2RedirectIndexRoute
  '/organizer/$orgId': typeof OrganizerOrgIdIndexRoute
  '/organizer/check-in': typeof OrganizerCheckInIndexRoute
  '/event/$eventId/payment': typeof EventEventIdPaymentIndexRoute
  '/organizer/$orgId/check-in': typeof OrganizerOrgIdCheckInIndexRoute
  '/event/$eventId/payment/confirm': typeof EventEventIdPaymentConfirmIndexRoute
  '/organizer/$orgId/event/$eventId': typeof OrganizerOrgIdEventEventIdIndexRoute
  '/organizer/$orgId/event/$eventId/check-in': typeof OrganizerOrgIdEventEventIdCheckInIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-tickets': typeof MyTicketsIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/payment-result': typeof PaymentResultIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/event/$eventId': typeof EventEventIdIndexRoute
  '/oauth2/redirect': typeof Oauth2RedirectIndexRoute
  '/organizer/$orgId': typeof OrganizerOrgIdIndexRoute
  '/organizer/check-in': typeof OrganizerCheckInIndexRoute
  '/event/$eventId/payment': typeof EventEventIdPaymentIndexRoute
  '/organizer/$orgId/check-in': typeof OrganizerOrgIdCheckInIndexRoute
  '/event/$eventId/payment/confirm': typeof EventEventIdPaymentConfirmIndexRoute
  '/organizer/$orgId/event/$eventId': typeof OrganizerOrgIdEventEventIdIndexRoute
  '/organizer/$orgId/event/$eventId/check-in': typeof OrganizerOrgIdEventEventIdCheckInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRouteRouteWithChildren
  '/my-tickets/': typeof MyTicketsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/payment-result/': typeof PaymentResultIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/event/$eventId/': typeof EventEventIdIndexRoute
  '/oauth2/redirect/': typeof Oauth2RedirectIndexRoute
  '/organizer/$orgId/': typeof OrganizerOrgIdIndexRoute
  '/organizer/check-in/': typeof OrganizerCheckInIndexRoute
  '/event/$eventId/payment/': typeof EventEventIdPaymentIndexRoute
  '/organizer/$orgId/check-in/': typeof OrganizerOrgIdCheckInIndexRoute
  '/event/$eventId/payment/confirm/': typeof EventEventIdPaymentConfirmIndexRoute
  '/organizer/$orgId/event/$eventId/': typeof OrganizerOrgIdEventEventIdIndexRoute
  '/organizer/$orgId/event/$eventId/check-in/': typeof OrganizerOrgIdEventEventIdCheckInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizer'
    | '/my-tickets'
    | '/organizer/'
    | '/payment-result'
    | '/resources'
    | '/event/$eventId'
    | '/oauth2/redirect'
    | '/organizer/$orgId'
    | '/organizer/check-in'
    | '/event/$eventId/payment'
    | '/organizer/$orgId/check-in'
    | '/event/$eventId/payment/confirm'
    | '/organizer/$orgId/event/$eventId'
    | '/organizer/$orgId/event/$eventId/check-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-tickets'
    | '/organizer'
    | '/payment-result'
    | '/resources'
    | '/event/$eventId'
    | '/oauth2/redirect'
    | '/organizer/$orgId'
    | '/organizer/check-in'
    | '/event/$eventId/payment'
    | '/organizer/$orgId/check-in'
    | '/event/$eventId/payment/confirm'
    | '/organizer/$orgId/event/$eventId'
    | '/organizer/$orgId/event/$eventId/check-in'
  id:
    | '__root__'
    | '/'
    | '/organizer'
    | '/my-tickets/'
    | '/organizer/'
    | '/payment-result/'
    | '/resources/'
    | '/event/$eventId/'
    | '/oauth2/redirect/'
    | '/organizer/$orgId/'
    | '/organizer/check-in/'
    | '/event/$eventId/payment/'
    | '/organizer/$orgId/check-in/'
    | '/event/$eventId/payment/confirm/'
    | '/organizer/$orgId/event/$eventId/'
    | '/organizer/$orgId/event/$eventId/check-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizerRouteRoute: typeof OrganizerRouteRouteWithChildren
  MyTicketsIndexRoute: typeof MyTicketsIndexRoute
  PaymentResultIndexRoute: typeof PaymentResultIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  EventEventIdIndexRoute: typeof EventEventIdIndexRoute
  Oauth2RedirectIndexRoute: typeof Oauth2RedirectIndexRoute
  EventEventIdPaymentIndexRoute: typeof EventEventIdPaymentIndexRoute
  EventEventIdPaymentConfirmIndexRoute: typeof EventEventIdPaymentConfirmIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-result/': {
      id: '/payment-result/'
      path: '/payment-result'
      fullPath: '/payment-result'
      preLoaderRoute: typeof PaymentResultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/my-tickets/': {
      id: '/my-tickets/'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/check-in/': {
      id: '/organizer/check-in/'
      path: '/check-in'
      fullPath: '/organizer/check-in'
      preLoaderRoute: typeof OrganizerCheckInIndexRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/organizer/$orgId/': {
      id: '/organizer/$orgId/'
      path: '/$orgId'
      fullPath: '/organizer/$orgId'
      preLoaderRoute: typeof OrganizerOrgIdIndexRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/oauth2/redirect/': {
      id: '/oauth2/redirect/'
      path: '/oauth2/redirect'
      fullPath: '/oauth2/redirect'
      preLoaderRoute: typeof Oauth2RedirectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId/': {
      id: '/event/$eventId/'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/$orgId/check-in/': {
      id: '/organizer/$orgId/check-in/'
      path: '/$orgId/check-in'
      fullPath: '/organizer/$orgId/check-in'
      preLoaderRoute: typeof OrganizerOrgIdCheckInIndexRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/event/$eventId/payment/': {
      id: '/event/$eventId/payment/'
      path: '/event/$eventId/payment'
      fullPath: '/event/$eventId/payment'
      preLoaderRoute: typeof EventEventIdPaymentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/$orgId/event/$eventId/': {
      id: '/organizer/$orgId/event/$eventId/'
      path: '/$orgId/event/$eventId'
      fullPath: '/organizer/$orgId/event/$eventId'
      preLoaderRoute: typeof OrganizerOrgIdEventEventIdIndexRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
    '/event/$eventId/payment/confirm/': {
      id: '/event/$eventId/payment/confirm/'
      path: '/event/$eventId/payment/confirm'
      fullPath: '/event/$eventId/payment/confirm'
      preLoaderRoute: typeof EventEventIdPaymentConfirmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/$orgId/event/$eventId/check-in/': {
      id: '/organizer/$orgId/event/$eventId/check-in/'
      path: '/$orgId/event/$eventId/check-in'
      fullPath: '/organizer/$orgId/event/$eventId/check-in'
      preLoaderRoute: typeof OrganizerOrgIdEventEventIdCheckInIndexRouteImport
      parentRoute: typeof OrganizerRouteRoute
    }
  }
}

interface OrganizerRouteRouteChildren {
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  OrganizerOrgIdIndexRoute: typeof OrganizerOrgIdIndexRoute
  OrganizerCheckInIndexRoute: typeof OrganizerCheckInIndexRoute
  OrganizerOrgIdCheckInIndexRoute: typeof OrganizerOrgIdCheckInIndexRoute
  OrganizerOrgIdEventEventIdIndexRoute: typeof OrganizerOrgIdEventEventIdIndexRoute
  OrganizerOrgIdEventEventIdCheckInIndexRoute: typeof OrganizerOrgIdEventEventIdCheckInIndexRoute
}

const OrganizerRouteRouteChildren: OrganizerRouteRouteChildren = {
  OrganizerIndexRoute: OrganizerIndexRoute,
  OrganizerOrgIdIndexRoute: OrganizerOrgIdIndexRoute,
  OrganizerCheckInIndexRoute: OrganizerCheckInIndexRoute,
  OrganizerOrgIdCheckInIndexRoute: OrganizerOrgIdCheckInIndexRoute,
  OrganizerOrgIdEventEventIdIndexRoute: OrganizerOrgIdEventEventIdIndexRoute,
  OrganizerOrgIdEventEventIdCheckInIndexRoute:
    OrganizerOrgIdEventEventIdCheckInIndexRoute,
}

const OrganizerRouteRouteWithChildren = OrganizerRouteRoute._addFileChildren(
  OrganizerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizerRouteRoute: OrganizerRouteRouteWithChildren,
  MyTicketsIndexRoute: MyTicketsIndexRoute,
  PaymentResultIndexRoute: PaymentResultIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  EventEventIdIndexRoute: EventEventIdIndexRoute,
  Oauth2RedirectIndexRoute: Oauth2RedirectIndexRoute,
  EventEventIdPaymentIndexRoute: EventEventIdPaymentIndexRoute,
  EventEventIdPaymentConfirmIndexRoute: EventEventIdPaymentConfirmIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
