/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as MyCalendarIndexRouteImport } from './routes/my-calendar/index';

const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any);
const MyCalendarIndexRoute = MyCalendarIndexRouteImport.update({
    id: '/my-calendar/',
    path: '/my-calendar/',
    getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute;
    '/my-calendar': typeof MyCalendarIndexRoute;
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute;
    '/my-calendar': typeof MyCalendarIndexRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    '/': typeof IndexRoute;
    '/my-calendar/': typeof MyCalendarIndexRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: '/' | '/my-calendar';
    fileRoutesByTo: FileRoutesByTo;
    to: '/' | '/my-calendar';
    id: '__root__' | '/' | '/my-calendar/';
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    MyCalendarIndexRoute: typeof MyCalendarIndexRoute;
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            id: '/';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/my-calendar/': {
            id: '/my-calendar/';
            path: '/my-calendar';
            fullPath: '/my-calendar';
            preLoaderRoute: typeof MyCalendarIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    MyCalendarIndexRoute: MyCalendarIndexRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();
